version: "3"

services:
  vpcProvisioner-pr:
    container_name: ec2c-proxy
    image: nginx:1.26.1-alpine
    hostname: ec2c-proxy
    ports:
      - "443:443"
    networks:
      dockernet:
        ipv4_address: 10.20.20.155
    volumes:
      - './conf.d/:/etc/nginx/conf.d/'
      - './certs/:/etc/nginx/certs/'
      - './logs/:/var/log/nginx'
    restart: unless-stopped
    environment:
     - TZ=Europe/Athens    

networks:
  dockernet:
    name: dockernet
    external: true